attack: fgsm
attack-norm: l1
model_dir: /Users/noah/Dev/adversarial_rl/models  # must be absolute path
eval_steps: 1e7
attack:
  grid_search: ['fgsm', 'random']
alg:
  grid_search: ['dqn', 'trpo_mpi', 'ppo2', 'a2c']
eps:
  grid_search: [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
env:
  grid_search: ['ChopperCommandNoFrameskip-v0', 'PongNoFrameskip-v0', 'SeaquestNoFrameskip-v0', 'SpaceInvadersNoFrameskip-v0']
